services:
  tensorflow_gpu:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    entrypoint: bash
    restart: "no"
    volumes:
      - ../../:/workspace
    working_dir: /workspace
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: all
    runtime: nvidia
