services:
  tensorflow_gpu:
    build:
      context: .            # tells it to use local Dockerfile
      dockerfile: Dockerfile_GPU
    #image: tensorflow/tensorflow:latest-gpu
    stdin_open: true
    tty: true
    entrypoint: bash
    restart: "no"
    volumes:
      - ./:/workspace
    working_dir: /workspace
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
